// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjyqzmcvlsdtxjkvzcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ianlxem1jdmxzZHR4amt2emN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjYxNjQsImV4cCI6MjA2MTEwMjE2NH0.a_kNBnYJxQtbasQv8cG__T7lJ_BSKY5KKpFjTDCjfRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);